[package]
name = "fees"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version ="0.11.23", features = ["blocking"] }
rust_decimal = "1.33.1"
